---
title: "fit_crcvm"
author: "Alexandre Delporte"
date: "2024-12-12"
output: html_document
---
To circumvent this issue, we can fix a smooth parametric function for $\omega$, based on the observed distances to shore and the observed angular velocities.

# Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,message=FALSE}
set.seed(42)

library(smoothSDE)
library(ggplot2)
library(dplyr)
library(plotly)
library(htmlwidgets)
library(mgcv)
library(here)
library(xtable)
library(sf)
library(gganimate) # animated trajectories
```

```{r get data,message=FALSE}

# Set the path to the directory containing the data
par_dir=here() #parent directory 
narwhal_data_path <- file.path(par_dir,"Data","preprocessed_data","narwhals")  

#data before exposure with first 24h removed
dataBE24=read.csv(file.path(narwhal_data_path,"DataBE1.csv"), header = TRUE,dec = ".")

#data before exposure with first 12h removed
dataBE12=read.csv(file.path(narwhal_data_path,"DataBE2.csv"), header = TRUE,dec = ".")

#data after exposure
dataAE=read.csv(file.path(narwhal_data_path,"DataAE.csv"), header = TRUE,dec = ".")

```


```{r}

N=length(unique(dataBE12$ID))

n_pre12=length(dataBE12$time) #number of observations before exposure
n_pre24=length(dataBE24$time) #number of observations before exposure
n_post=length(dataAE$time) #number of observations after exposure
```


```{r}

plot_Dshore=ggplot(data=dataBE12)+geom_point(aes(x=time,y=DistanceShore,col=ID),size=1,alpha=0.5)+
  geom_line(aes(x=time,y=DistanceShore,col=ID),size=1,alpha=0.2)+
  theme_minimal()

ggsave("observed_Dshore.pdf",plot=plot_Dshore)

quantile(dataBE12$DistanceShore,probs=0.05)

```

```{r}
dataBE12$angular_velocity=c(NA,diff(dataBE12$AngleNormal)/diff(dataBE12$time))
plot_angular_velocity=ggplot(data=dataBE12)+geom_point(aes(x=time,y=angular_velocity,col=ID),size=1,alpha=0.5)+
  geom_line(aes(x=time,y=angular_velocity,col=ID),size=1,alpha=0.2)+
  theme_minimal()
ggsave("observed_angular_velocity.pdf",plot=plot_angular_velocity)
max(dataBE12$angular_velocity,na.rm=TRUE)/(pi*(pi-pi/2)*(pi+pi/2)*exp(-1))



```

```{r}

renamed_dataBE12=dataBE12
colnames(renamed_dataBE12)[48]="theta"
renamed_dataBE12[renamed_dataBE12$DistanceShore==0,]=0.02


#Fixed measurement error
sigma_obs=0.03
H=array(rep(sigma_obs^2*diag(2),n_pre12),dim=c(2,2,n_pre12))

#parameters formulas
formulas <- list(tau =~s(ID,bs="re"),nu=~s(ID,bs="re"),
                   a=~1,b=~1,D0=~1,D1=~1,sigma_D=~1,sigma_theta=~1)

# Fit baseline
baseline_crcvm_cubic<- SDE$new(formulas = formulas,data = renamed_dataBE12,type = "CRCVM_SSM",
                    response = c("x","y"),par0 = c(1,4,0.1,4,0.2,0.5,0.1,pi/6),other_data=list("H"=H),
                    fixpar=c("a","b","D0","D1","sigma_D","sigma_theta"))

baseline_crcvm_cubic$fit()


```


```{r}
plots_bas_crcvm=baseline_crcvm_cubic$get_all_plots(baseline=NULL,show_CI="simultaneous")

plots_bas_crcvm
```

