---
title: "fit_crcvm"
author: "Alexandre Delporte"
date: "2024-12-12"
output: html_document
---

We fit the CRCVM defined in the paper on the narwhal data.

# Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,message=FALSE}

library(smoothSDE)
library(ggplot2)
library(dplyr)
library(plotly)
library(htmlwidgets)
library(mgcv)
library(here)
library(xtable)
library(sf)
library(gganimate)
library(doParallel)
library(foreach)
library(ggpubr)
library(fitdistrplus)
```

# Read data

```{r get data,message=FALSE,}

# Set the path to the directory containing the data
par_dir=here() #parent directory 

narwhal_data_path <- file.path(par_dir,"Data","preprocessed_data","narwhals")  

#data before exposure with first 12h removed
dataBE12=read.csv(file.path(narwhal_data_path,"DataBE12.csv"), header = TRUE,dec = ".")

#data after exposure
dataAE=read.csv(file.path(narwhal_data_path,"DataAE.csv"), header = TRUE,dec = ".")


```

```{r get border,message=FALSE}
# Set the path to the directory containing the greenland data
greenland_data_path <- here("Data","preprocessed_data","greenland")


border200<-st_read(file.path(greenland_data_path,"shrunk200_scoresby_sound_utm.shp"))
border200 <- st_transform(border200, crs = "+init=EPSG:32626 +units=km")

```

```{r}

N=length(unique(dataBE12$ID)) #number of ID
n_pre=nrow(dataBE12) #number of observations before exposure
n_post=nrow(dataAE) #number of observations after exposure

```


# Utility functions

```{r define function to plot interpolation}

#' Plot interpolated trajectories, angles and distances
#' @param data Dataframe with the columns time, ID, BoundaryDistance, and BoundaryAngle
#' @param interpolation_data 
#' @param border Boundary of the domain as a sf object with geometry 
#' @param response name of response variables
#' @return List of plots
get_interpolation_plots<-function(data,interpolation_data,border,response=c("x","y")) {
  
  
  #create dataframe with interpolated values
  end_indices <- c(which(diff(as.numeric(factor(data$ID))) != 0),nrow(data))
  n_step<-ncol(interpolation_data$BoundaryDistance)
  interpolated_x_vec=as.vector(t(interpolation_data[[response[1]]][-end_indices,]))
  interpolated_y_vec=as.vector(t(interpolation_data[[response[2]]][-end_indices,]))
  interpolated_distance_vec=as.vector(t(interpolation_data$BoundaryDistance[-end_indices,]))
  interpolated_angle_vec=as.vector(t(interpolation_data$BoundaryAngle[-end_indices,]))
  interpolation_time=as.vector(t(interpolation_data$time[-end_indices,]))
  ID=unlist(lapply(unique(data$ID), function(id) {
    n=nrow(data[data$ID==id,])
    rep(id,(n-1)*n_step)
  }))
  
  #combine dataframes
  interpolated_df=data.frame("time"=interpolation_time,"ID"=ID,"x"=interpolated_x_vec,
                             "y"=interpolated_y_vec,
                             "BoundaryDistance"=interpolated_distance_vec,
                             "BoundaryAngle"=interpolated_angle_vec)
  interpolated_df$type="Interpolated"
  data$type="Observed"
  colnames(data)[colnames(data)==response[1]]<-"x"
  colnames(data)[colnames(data)==response[2]]<-"y"
  
  combined_data<-rbind(interpolated_df,data)
  
  
  # Create plot with legends for shape and linetype
  trajectory_plot = ggplot() +geom_sf(data=border$geometry,fill="grey")+
    geom_point(data = combined_data, 
               aes(x,y, col = ID, shape = type), size = 0.2,alpha=1) +
    
    # Customize the legend
    labs(color = "Trajectory ID", 
         shape = "Point Type", 
         linetype = "Line Type", 
         title = "Interpolated vs. Observed trajectories") +
    scale_shape_manual(values = c(10:12))+
    theme_minimal() +
    theme(legend.position = "right")  # Adjust legend position
  
  
  
  distance_plot = ggplot() +
    # Scatter plot for observed BoundaryDistance (Shape Legend)
    geom_line(data = combined_data, 
               aes(time, BoundaryDistance, col = ID, linetype = type), size = 0.5) +
    
    # Customize the legend
    labs(color = "Trajectory ID", 
         shape = "Point Type", 
         linetype = "Line Type", 
         x = "Time", y = "Boundary Distance", 
         title = "Interpolated vs. True Boundary Distance") +
    
    theme_minimal() +
    theme(legend.position = "right")  # Adjust legend position
  
  
  # Create plot with legends for shape and linetype
  angle_plot = ggplot() +
    # Scatter plot for observed BoundaryDistance (Shape Legend)
    geom_line(data = combined_data, 
               aes(time, BoundaryAngle, col = ID, linetype = type), size = 0.5) +
    
    # Customize the legend
    labs(color = "Trajectory ID", 
         shape = "Point Type", 
         linetype = "Line Type", 
         x = "Time", y = "Boundary Angle", 
         title = "Interpolated vs. True Boundary Angle") +
    
    theme_minimal() +
    theme(legend.position = "right")  # Adjust legend position
  
  return(list("angle_plot"=angle_plot,"distance_plot"=distance_plot,"trajectory_plot"=trajectory_plot))
}


```



```{r define function to fit the baseline model}

#' Fit baseline on data
#' @param data data before exposure 
#' @param interpolation_data 
#' @param sigma_obs GPS measurement error std
#' @param a,b,D0,D1,sigma_D,sigma_theta parameters in the function omega
#' @param fixpar parameters to fix
#' @param response name of response variables
#' @return Fitted baseline SDE object
fit_baseline<-function(data,interpolation_data,sigma_obs=0.05,a=2,b=1,D0=0.3,D1=0.5,
                       sigma_D=1,sigma_theta=0.6,fixpar=c("a","b","D0","D1","sigma_D","sigma_theta"),
                       response=c("x","y")) {
  
  #Fixed measurement error
  H=array(rep(sigma_obs^2*diag(2),length(data$time)),dim=c(2,2,length(data$time)))
  
  interpolated_dist<- interpolation_data$BoundaryDistance
  interpolated_dist[interpolated_dist == 0] <- 0.1
  
  #parameters formulas
  formulas <- list(tau =~s(ID,bs="re"),nu=~s(ID,bs="re"),
                   a=~1,b=~1,D0=~1,D1=~1,sigma_D=~1,sigma_theta=~1)
  
  # Fit baseline
  baseline <- SDE$new(formulas = formulas,
                              data = data,type = "CRCVM_SSM",
                              response = response,par0 = c(1.2,4.5,a,b,D0,D1,sigma_D,sigma_theta),
                              fixpar=fixpar,
                              other_data=
                                list("H"=H,"interpolated_distance"=interpolated_dist,
                                     "interpolated_angle"=interpolation_data$BoundaryAngle))
  baseline$update_lambda(c(1,1))
  baseline$fit()
  
  return (baseline)
}


```



```{r define function to get the estimates of the fitted model}

#' Get estimated from fitted baseline SDE model
#' @param sde fitted sde
#' @param include_sigma_obs boolean
#' @param n_post number of draws from the posterior distribution used to give estimates
#' and confidence intervals
#' @param resp Logical (default: TRUE). Should the output be on 
#' the response scale? If FALSE, the output is on the linear 
#' predictor scale
#' @return List of estimates, standard error and quantiles for each parameter
get_baseline_estimates<- function(sde,include_sigma_obs=FALSE,n_post=100,
                                  resp=FALSE) {
  
  post_coeff=sde$post_coeff(n_post=n_post)
  link=ifelse(resp,exp,identity)
  post_par=list(
  "tau"=link(post_coeff$coeff_fe[,"tau.(Intercept)"]),
  "nu"=link(post_coeff$coeff_fe[,"nu.(Intercept)"]),
  "sigma_tau"=1/sqrt(exp(post_coeff$log_lambda[,"tau.s(ID)"])),
  "sigma_nu"=1/sqrt(exp(post_coeff$log_lambda[,"nu.s(ID)"])))
  
  if (include_sigma_obs) {
    post_par$sigma_obs=1000*exp(post_coeff$log_sigma_obs)
  }

  mean_par=lapply(post_par,mean)
  sd_par=lapply(post_par,sd)
  quant_par <- lapply(post_par,
                      quantile, probs = c(0.025, 0.975))
  
  return(list("estimates"=mean_par,"std.error"=sd_par,"quantiles"=quant_par))
  
}

#' Make latex table to show the estimates and confidence intervals
#' @param sde fitted sde
#' @param include_sigma_obs boolean
#' @param n_post number of draws from the posterior distribution used to give estimates
#' and confidence intervals
#' @return NULL (just print latex table)
make_final_baseline_tab<-function(sde,include_sigma_obs=FALSE,n_post=100,resp=FALSE) {
  
  est=get_baseline_estimates(sde,include_sigma_obs,n_post,resp)
  mean_par=est$estimates
  sd_par=est$std.error
  quant_par=est$quantiles
  parameter_names <- names(mean_par)
  estimates <- mean_par
  conf_intervals <- sapply(parameter_names, function(param) {
  sprintf("$[%.2f; %.2f]$", quant_par[[param]][1], 
          quant_par[[param]][2])
    })
  
  parameter_names=c("$\\tau$", "$\\nu$","$\\sigma_{\\tau}$","$\\sigma_{\\nu}$")
  if (include_sigma_obs) {
    parameter_names=c(parameter_names,"$\\sigma_{\\obs}$")
  }
  table_data <- data.frame(
    Parameter = parameter_names,
  Estimate = sprintf("$%.2f$", mean_par),
  CI = conf_intervals,
  stringsAsFactors = FALSE)
  
  xtab <- xtable(
  table_data,
  caption = paste(sde$type(),"baseline estimations with random effects"),
  label = paste0("table:",sde$type(),"_baseline_estimations_with_random_effects"))
  
  print(
  xtab,type="latex",
  include.rownames = FALSE,
  sanitize.text.function = identity,  # Prevent escaping of LaTeX math symbols
  hline.after = c(-1, 0, nrow(table_data)),  
  table.placement="H")

} 

```

```{r define functions to compare simulation and observations}

#' Make plot to compare distributions in simulation and observation
#' @param simulated_data list of data frames simulated from an SDE model, each containing columns "BoundaryDistance", "BoundaryAngle" and "speed"
#' @param observed_data real GPS data (data frame).
#' @return ggplot of boundary distances distributions
make_density_plots <- function(simulated_data, observed_data) {
  
  # Ensure simulated_data is a list of data frames
  if (!is.list(simulated_data) || !all(sapply(simulated_data, is.data.frame))) {
    stop("simulated_data must be a list of data frames")
  }

  # drop trajectories that reached land
  
  simulated_combined <- bind_rows(
    lapply(seq_along(simulated_data), function(i) {
      simulated_data[[i]] %>% mutate(SimulationID = as.factor(i), Source = "Simulated")
    })
  )
  
  
  observed_combined <- observed_data %>% mutate(Source = "Observed")
  
  combined_data <- bind_rows(simulated_combined, observed_combined)

  # Plot density distribution
  plot_distance <- ggplot(combined_data, aes(x = BoundaryDistance, color = Source, fill = Source)) +
    geom_density(data = simulated_combined, aes(group = SimulationID), alpha = 0.1) + 
    geom_density(data = observed_combined, alpha = 0.2) +
    xlab("Distance to Shore") +
    scale_color_manual(values = c("Simulated" = "blue", "Observed" = "red")) + 
    scale_fill_manual(values = c("Simulated" = "blue", "Observed" = "red")) +
    theme(
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 20),
    axis.title.y = element_blank(),
    axis.title.x = element_blank())
    theme(legend.title = element_blank())
    
    plot_angle <- ggplot(combined_data, aes(x = abs(BoundaryAngle), color = Source, 
                                            fill = Source)) +
    geom_density(data = simulated_combined, aes(group = SimulationID), 
                 alpha = 0.1) + 
    geom_density(data = observed_combined, alpha = 0.2) + 
    xlab(expression(Theta)) +
    scale_color_manual(values = c("Simulated" = "blue", "Observed" = "red")) + 
    scale_fill_manual(values = c("Simulated" = "blue", "Observed" = "red")) +
    theme(
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 20),
    axis.title.y = element_blank(),
    axis.title.x = element_blank())
    theme(legend.title = element_blank())
    
    plot_speed <- ggplot(combined_data, aes(x = speed, color = Source, 
                                            fill = Source)) +
    geom_density(data = simulated_combined, aes(group = SimulationID), 
                 alpha = 0.1) + 
    geom_density(data = observed_combined, alpha = 0.2) + 
    xlab("Speed") +
    scale_color_manual(values = c("Simulated" = "blue", "Observed" = "red")) + 
    scale_fill_manual(values = c("Simulated" = "blue", "Observed" = "red")) +
  theme(
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 20),
    axis.title.y = element_blank(),
    axis.title.x = element_blank())
    theme(legend.title = element_blank())


  return(list("distance"=plot_distance,"speed"=plot_speed,"angle"=plot_angle))
}

#' Compute empirical speed from finite differences
#' @param data data with column time
#' @param response name of response variables
#' @return vector of empirical speeds
compute_speed<-function(data,response=c("x","y")) {
  
  speed_vector<-rep(0,nrow(data))
  
  for (id in unique(data$ID)){
  
    #filter data with specific id
    sub_ind=(data$ID==id)
    sub_data=data[sub_ind,]
    n_sub=length(sub_data$time)
  
    #time steps
    dtimes=sub_data[2:n_sub,"time"]-sub_data[1:(n_sub-1),"time"]
  
    #step lengths
    dx=sub_data[2:n_sub,response[1]]-sub_data[1:(n_sub-1),response[1]]
    dy=sub_data[2:n_sub,response[2]]-sub_data[1:(n_sub-1),response[2]]
  
    speed=c(NA,sqrt((dx/dtimes)^2+(dy/dtimes)^2))
    
    speed_vector[sub_ind]<-speed
  }
  
  return(speed_vector)
}

```


# Fit baseline on data before exposure

```{r interpolate positions befor exposure}

#prepare data for interpolation
dataBE12_prep200=dataBE12[,c("ID","x","y","time","theta200","DistanceShore200")]

colnames(dataBE12_prep200)[colnames(dataBE12_prep200)=="DistanceShore200"]<-"BoundaryDistance"
colnames(dataBE12_prep200)[colnames(dataBE12_prep200)=="theta200"]<-"BoundaryAngle"

#remove points on land
dataBE12_prep200<-dataBE12_prep200[dataBE12_prep200$BoundaryDistance>0,]

n_step=15

#compute spline interpolation
interpolation_bas_200<-interpolate_BoundaryMetrics(dataBE12_prep200,response=c("x","y"),
                                                border200,n_step=n_step,n_cores=6,df_ratio=0.95)
```


```{r}
interpolation_plots<-get_interpolation_plots(dataBE12_prep200,interpolation_bas_200,border200)

interpolation_plots
```


```{r}
D0=quantile(dataBE12_prep200$BoundaryDistance,0.9)
D1=quantile(dataBE12_prep200$BoundaryDistance,0.75)
a=0.22*D0

baseline_crcvm200<- fit_baseline(dataBE12_prep200,interpolation_bas_200,
                    b=2,a=a,sigma_D=1,D0=D0,D1=D1,sigma_theta=pi/6,
                    sigma_obs=0.05)

```


```{r}
baseline_crcvm200$get_all_plots(baseline=NULL,show_CI="simultaneous")
```

```{r}
make_final_baseline_tab(baseline_crcvm200,include_sigma_obs=FALSE,n_post=100)
```


# Check baseline model

## Simulate trajectories

```{r set up for simulation}

#initial narwhals positions (convert to matrix to avoid bugs)
z0_BE <- as.matrix(dataBE12_prep200[!duplicated(dataBE12_prep200$ID), c("x", "y")])

# Define functions to compute covariates along the way
fangle=function(z,v,p) {
  
  #normal vector
  normal=c(z[1]-p[1],z[2]-p[2])
  
  #return angle
  return (signed_angle(normal,v))
}


fDshore=function(z,v,p) {

  #normal vector
  normal=c(z[1]-p[1],z[2]-p[2])
  
  #distance to shore
  Dshore=sqrt(normal[1]^2+normal[2]^2)
  
  #fix a threshold to avoid error when we hit the boundary
  if (Dshore>0.005) {
      return(Dshore)
  }
  else {
    return(0.005)
  }

}

atw=list("BoundaryAngle"=fangle,"BoundaryDistance"=fDshore)


# Define time steps
delta=1/60/6
times_list=lapply(unique(dataBE12_prep200$ID),function(ID) {
  min=min(dataBE12[dataBE12_prep200$ID==ID,"time"])
  max=max(dataBE12[dataBE12_prep200$ID==ID,"time"])
  seq(min,max,by=delta)})
names(times_list)=unique(dataBE12_prep200$ID)
times_df <- data.frame(
  ID = rep(names(times_list), sapply(times_list, length)),
  time = unlist(times_list),row.names = NULL
)
n=length(times_df$time)
# Define covariates data (needed in the function simulate)
data_reg=data.frame("BoundaryDistance"=rep(1,n),
                    "BoundaryAngle"=rep(0,n))

data_reg=cbind(data_reg,times_df)

```


```{r simulate trajectory from baseline model}
all_sim=list()
n_sim=4

for (i in 1:n_sim) {
  set.seed(i)
  baseline_crcvm200_trajectory=baseline_crcvm200$simulate(z0=z0_BE,
                     data=data_reg,atw=atw,land=border200,verbose=FALSE,n_cores=6)
  colnames(baseline_crcvm200_trajectory)[colnames(baseline_crcvm200_trajectory)=="z1"]<-"x"
  colnames(baseline_crcvm200_trajectory)[colnames(baseline_crcvm200_trajectory)=="z2"]<-"y"
  
  all_sim[[i]]<-baseline_crcvm200_trajectory

}

```


## Simulate time steps


```{r reproduce realistic time steps,warning=FALSE,message=FALSE}

dtimes<-unlist(lapply(unique(dataBE12_prep200$ID),function(id) {
    sub_data<-dataBE12_prep200[dataBE12_prep200$ID==id,]
    dt=diff(sub_data$time)
    dt
}))

fit_lognorm <- fitdist(dtimes * 60, "lnorm")
fit_gamma <- fitdist(dtimes * 60, "gamma")
gofstat(list(fit_lognorm,fit_gamma))

```

```{r}
# Extract estimated parameters
meanlog <- fit_lognorm$estimate["meanlog"]
sdlog <- fit_lognorm$estimate["sdlog"]

# Generate new time steps
dtimes_sim <- rlnorm(nrow(dataBE12_prep200)-6, meanlog, sdlog)

times_sim<-lapply(unique(dataBE12_prep200$ID),function(ID) {
  sub_time<- dataBE12_prep200[dataBE12_prep200$ID==ID,"time"]
  sub_n<-length(sub_time)
  min_time=min(sub_time)
  times<-rep(min_time,sub_n)+c(0,cumsum(dtimes_sim[1:(sub_n-1)]/60))
  return (times)})
names(times_sim)<-unique(dataBE12_prep200$ID)
```



## Subsample and interpolate simulated trajectory

```{r}
all_sim_sub=list()

for (i in seq_along(all_sim)) {
  sim_data<-all_sim[[i]]
  interp_sim_data<-dataBE12_prep200[,c("time","ID","x","y")]
  interp_sim_data$time<-unlist(times_sim)

  for (id in unique(sim_data$ID)) {
    sub_sim_data<-sim_data[sim_data$ID==id,]
    sim_x_interp <- approx(sub_sim_data$time, sub_sim_data$x, xout = times_sim[[id]])$y
    sim_y_interp <- approx(sub_sim_data$time, sub_sim_data$y, xout = times_sim[[id]])$y
    sub_ind=interp_sim_data$ID==id
    interp_sim_data[sub_ind,"x"]<-sim_x_interp
    interp_sim_data[sub_ind,"y"]<-sim_y_interp
  }
  
  all_sim_sub[[i]]<-interp_sim_data
}
```

```{r subsample simulations}
#subsample to 5 minutes and add measurement noise
all_sim_sub<-lapply(all_sim_sub,function(data) {
  
  data<-data[!(is.na(data$x)),]
  noise<-rmvn(nrow(data),rep(0,2),diag(rep(0.02^2,2)))

  data[,c("x","y")]=data[,c("x","y")]+noise
  return (data)
})


```

```{r plot one simulated trajectory}

plot_sim_trajectory=ggplot() +
  geom_sf(data=border200$geometry,fill="grey")+
  coord_sf(datum=st_crs("+init=EPSG:32626 +units=km"))+
  geom_path(data=all_sim_sub[[2]], 
            aes(x = x, y = y,color=ID),size = 0.2, 
            lineend = "round",alpha=0.5) +     
  geom_point(data=all_sim_sub[[2]],
             aes(x = x, y = y,color=ID),size =0.2 ) +
  theme_minimal()+
  scale_color_viridis_d(name="ID",labels=c("A1","A2","A3","A4","A5","A6"))+theme(
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.text = element_text(size = 14),
    axis.title.y = element_blank(),
    axis.title.x = element_blank())

plot_obs_trajectory=ggplot() +
  geom_sf(data=border200$geometry,fill="grey")+
  coord_sf(datum=st_crs("+init=EPSG:32626 +units=km"))+
  geom_path(data=dataBE12, 
            aes(x = x, y = y,color=ID),size = 0.2, 
            lineend = "round",alpha=0.5) +     
  geom_point(data=dataBE12,
             aes(x = x, y = y,color=ID),size =0.2 ) +
  theme_minimal()+
  scale_color_viridis_d(name="ID",labels=c("A1","A2","A3","A4","A5","A6"))+theme(
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.text = element_text(size = 14),
    axis.title.y = element_blank(),
    axis.title.x = element_blank())


final_plot=ggarrange(plotlist=list(plot_obs_trajectory,plot_sim_trajectory),
                     ncol=2, nrow=1, common.legend = TRUE, legend="bottom",
                     labels= c("Observed","Simulated"), vjust=2)

ggsave(plot = final_plot, "sim_crcvm_trajectory.pdf", 
       width = 10, height = 6, units = "in", limitsize = FALSE)
```


```{r animate observed vs simulated trajectories}
dataBE12_prep200$type <- "Observed"
all_sim_sub[[2]]$type <- "Simulated"

combined_data <- rbind(dataBE12_prep200[,c("ID","time","x","y","type")], all_sim_sub[[2]])

combined_plot <- ggplot() +
  geom_sf(data=border200$geometry, fill="grey") +
  coord_sf(datum=st_crs("+init=EPSG:32626 +units=km")) +
  geom_path(data=combined_data, aes(x = x, y = y, color=ID, group=interaction(ID, type)), 
            size = 0.5, lineend = "round", alpha=0.5) +     
  geom_point(data=combined_data, aes(x = x, y = y, color=ID, shape=ID,group=interaction(ID, type)), 
             size = 0.5) +
  facet_wrap(~type) + 
  theme_minimal() +
  scale_color_viridis_d() +
  theme(axis.title = element_text(size = 18),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 18),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  transition_reveal(time)

animate(combined_plot, fps = 10, width = 800, height = 400)
anim_save("sim_crcvm_trajectory.gif")

```

```{r}
all_boundary_data<- lapply(all_sim_sub,function(data) {
  get_BoundaryMetrics(data,
                      response=c("x","y"),
                      border=border200)
})

for (i in seq_along(all_sim_sub)) {
  
  all_sim_sub[[i]][,c("BoundaryDistance","BoundaryAngle")]<- all_boundary_data[[i]]
  all_sim_sub[[i]]$speed<- compute_speed(data=all_sim_sub[[i]])
}


  
dataBE12_prep200$speed<-compute_speed(dataBE12_prep200)

plots<-make_density_plots(all_sim_sub,dataBE12_prep200) 

final_densities_plots<-ggarrange(plotlist=list(plots$distance,plots$angle),
                     ncol=2, nrow=1, common.legend = TRUE, legend="bottom", vjust=2)
ggsave("BoundaryDistance_density.pdf",path="baseline_crcvm_200",plot=plots$distance)
ggsave("BoundaryAngle_density.pdf",path="baseline_crcvm_200",plot=plots$angle)
ggsave("speed_density.pdf",path="baseline_crcvm_200",plot=plots$speed)
```





# Fit response

```{r}

#prepare data for interpolation
dataAE_prep200=dataAE[,c("ID","x","y","time","theta200","DistanceShore200","ExpShip")]

colnames(dataAE_prep200)[colnames(dataAE_prep200)=="DistanceShore200"]<-"BoundaryDistance"
colnames(dataAE_prep200)[colnames(dataAE_prep200)=="theta200"]<-"BoundaryAngle"

dataAE_prep200$speed<-compute_speed(dataAE_prep200)
#remove points on land
dataAE_prep200<-dataAE_prep200[dataAE_prep200$BoundaryDistance>0,]

n_step=15

#compute spline interpolation
interpolation_resp_200<-interpolate_BoundaryMetrics(dataAE_prep200,response=c("x","y"),
                                                border200,n_step=n_step,n_cores=6,df_ratio=0.95)

```


```{r}


fit_response<-function(baseline,data,interpolation_data,sigma_obs=0.05)  {
  
  
  #Fixed measurement error
  H=array(rep(sigma_obs^2*diag(2),nrow(data)),dim=c(2,2,nrow(data)))
  
  interpolated_distance<- interpolation_data$BoundaryDistance
  interpolated_distance[interpolated_distance == 0] <- 0.1
  
  #parameters formulas
  formulas <- list(tau =~ExpShip+s(ID,bs="re"),nu=~ExpShip+s(ID,bs="re"),
                     a=~1,b=~1,D0=~1,D1=~1,sigma_D=~1,sigma_theta=~1)
  
  # Create SDE object
  response_crcvm<- SDE$new(formulas = formulas,
                      data = data,type = "CRCVM_SSM",
                      response = c("x","y"),par0 = baseline$par(),
                      fixpar=c("a","b","D0","D1","sigma_theta","sigma_D"),
                      other_data=
                        list("H"=H,"interpolated_distance"=interpolated_distance,
                        "interpolated_angle"=interpolation_data$BoundaryAngle))
  
  
  new_map=list(coeff_re=factor(rep(NA,12)),coeff_fe=factor(c(NA,1,NA,2,rep(NA,6))),
                               log_lambda=factor(c(NA,NA)))
  
  new_coeff_fe=c(baseline$coeff_fe()["tau.(Intercept)",1],0,baseline$coeff_fe()["nu.(Intercept)",1],0,
                 baseline$coeff_fe()[3:8,1])
  new_coeff_re=baseline$coeff_re()
  new_lambda=c(baseline$lambda())
  
  response_crcvm$update_map(new_map)
  response_crcvm$update_coeff_re(new_coeff_re)
  response_crcvm$update_coeff_fe(new_coeff_fe)
  response_crcvm$update_lambda(new_lambda)
  
  response_crcvm$fit()
  
  return (response_crcvm)
}


```


```{r}
response_crcvm<-fit_response(baseline_crcvm200,dataAE_prep200,interpolation_resp_200)


```

```{r}

#plot parameters
xmin=list("ExpShip"=1/60)
xmax=list("ExpShip"=1/5)
link=list("ExpShip"=(\(x) 1/x))
xlabel=list("ExpShip"="Distance to ship")

plots_resp_crcvm200=response_crcvm100$get_all_plots(baseline=baseline_crcvm200,show_CI="pointwise",xmin=xmin,xmax=xmax,link=link,xlabel=xlabel)

plots_resp_crcvm200
```



# Propagate 200m shrunk border baseline uncertainty


```{r, message=FALSE,results="hide"}

propagate_baseline_uncertainty<-function(baseline,data,interpolation_data,n_sim=100,sigma_obs=0.05) {

  #posterior samples of the coefficient of the baseline model
  post_coeff_bas=baseline$post_coeff(n_post=n_sim)
  post_coeff_re=post_coeff_bas$coeff_re
  post_coeff_fe=post_coeff_bas$coeff_fe
  post_coeff_lambda=exp(post_coeff_bas$log_lambda)
  
  #define model formulas
  formulas <- list(tau =~ExpShip+s(ID,bs="re"),
                   nu=~ExpShip+s(ID,bs="re"),a=~1,b=~1,D0=~1,
                   D1=~1,sigma_D=~1,sigma_theta=~1)
  
  #Fixed measurement error
  H=array(rep(sigma_obs^2*diag(2),nrow(data)),dim=c(2,2,nrow(data)))
  
  interpolated_distance<- interpolation_data$BoundaryDistance
  interpolated_distance[interpolated_distance == 0] <- 0.1
  
  # vector to store estimates and std
  alpha_estimates=matrix(rep(0,2*nrow(post_coeff_fe)),ncol=2)
  alpha_std=matrix(rep(0,2*nrow(post_coeff_fe)),ncol=2)
  
  #list to store models
  models_list=list()
  
  for (i in 1:nrow(post_coeff_fe)) {
    
      
          
      response_crcvm_temp<- SDE$new(formulas = formulas,
                          data = data,type = "CRCVM_SSM",
                          response = c("x","y"),par0 = baseline$par(),
                          fixpar=c("a","b","D0","D1","sigma_theta","sigma_D"),
                          other_data=
                            list("H"=H,"interpolated_distance"=interpolated_distance,
                            "interpolated_angle"=interpolation_data$BoundaryAngle))
      
      
      new_map=list(coeff_re=factor(rep(NA,12)),coeff_fe=factor(c(NA,1,NA,2,rep(NA,6))),
                                   log_lambda=factor(c(NA,NA)))
      
      new_coeff_fe=c(post_coeff_fe[i,"tau.(Intercept)"],0,post_coeff_fe[i,"nu.(Intercept)"],0,
                     post_coeff_fe[i,3:8])
      new_coeff_re=post_coeff_re[i,]
      new_lambda=post_coeff_lambda[i,]
      
      response_crcvm_temp$update_map(new_map)
      response_crcvm_temp$update_coeff_re(new_coeff_re)
      response_crcvm_temp$update_coeff_fe(new_coeff_fe)
      response_crcvm_temp$update_lambda(new_lambda)
      
      try(response_crcvm_temp$fit())
    
      est_alpha=as.list(response_crcvm_temp$tmb_rep(),what="Est")$coeff_fe[c("tau.ExpShip","nu.ExpShip"),1]
      std_alpha=as.list(response_crcvm_temp$tmb_rep(),what="Std")$coeff_fe[c("tau.ExpShip","nu.ExpShip"),1]
      
      alpha_estimates[i,]=est_alpha
      alpha_std[i,]=std_alpha
      
      models_list[[i]]=response_crcvm_temp
  }
  
  colnames(alpha_estimates)=c("tau.ExpShip","nu.ExpShip")
  colnames(alpha_std)=c("tau.ExpShip","nu.ExpShip")
  
  return(list("models"=models_list,"estimates"=alpha_estimates,"std"=alpha_std))
}

results_200_batch1<-propagate_baseline_uncertainty(baseline_crcvm200,dataAE_prep200,
                                        interpolation_resp_200,n_sim=50,sigma_obs=0.05)

```



```{r propagate uncertainty coefficient log -linear model}
alpha_estimates<- results_200_batch1$estimates


index<- rowSums(alpha_estimates == 0) < 2
alpha_estimates_filtered<-alpha_estimates[index, ]
mean_alpha=list(alpha_tau=mean(alpha_estimates_filtered[,1]),
                alpha_nu=mean(alpha_estimates_filtered[,2]))
quant_alpha<- list(
  alpha_tau=quantile(alpha_estimates_filtered[,1],probs = c(0.025, 0.975)),
  alpha_nu=quantile(alpha_estimates_filtered[,2],probs = c(0.025, 0.975)))

```

```{r propagated CI alpha log linear coefficients, message=FALSE}

parameter_names <- names(mean_alpha)
estimates <- mean_alpha
conf_intervals <- sapply(parameter_names, function(param) {
  sprintf("$[%.2f; %.2f]$", quant_alpha[[param]][1], 
          quant_alpha[[param]][2])
})


table_data <- data.frame(
  Parameter = 
    c("$\\alpha_{\\tau}$","$\\alpha_{\\nu}$"),
  Estimate = sprintf("$%.2f$", mean_alpha),
  CI = conf_intervals,
  stringsAsFactors = FALSE
)

```


```{r,results='asis',echo=FALSE}
xtab <- xtable(
  table_data,
  caption = "Response log linear estimations with propagated uncertainty",
  label = "table:response_log_linear_estimations_with_propagated_uncertainty"
)

print(
  xtab,type="latex",
  include.rownames = FALSE,
  sanitize.text.function = identity,  
  hline.after = c(-1, 0, nrow(table_data)),
  table.placement="H"
  
)
```





```{r all CI plots,cache=TRUE}
models_list_filtered<- results_200_batch1$models[index]
CI_plots=lapply(models_list_filtered,function(model) { 
  model$get_all_plots(baseline=NULL,xmin=xmin,xmax=xmax,
                      link=link,xlabel=xlabel,show_CI="pointwise")})


```

```{r plot smooth parameters with propagated uncertainty,results='hide'}

# Extract data for each estimated smooth parameter
tau_CI_data <- lapply(CI_plots, function(plot) {
  ggplot_build(plot$fe_tau_ExpShip)$data[[1]][,c("x","y")]
})
nu_CI_data <- lapply(CI_plots, function(plot) {
  ggplot_build(plot$fe_nu_ExpShip)$data[[1]][,c("x","y")]
})

# Get confidence intervals as quantiles of estimated parameters

# Combine the x columns from all data frames into a matrix
x_matrix_tau <- do.call(cbind, lapply(tau_CI_data, function(df) df$y))
x_matrix_nu <- do.call(cbind, lapply(nu_CI_data, function(df) df$y))
# Compute the 5% and 95% quantiles row-wise
quantiles_tau <- apply(x_matrix_tau, 1, 
                       function(row) quantile(row, probs = c(0.025, 0.975)))
quantiles_nu <- apply(x_matrix_nu, 1,
                      function(row) quantile(row, probs = c(0.025, 0.975)))

# Transpose and format the results into a data frame
quantiles_tau <- as.data.frame(t(quantiles_tau))
colnames(quantiles_tau) <- c("low", "up")
quantiles_nu <- as.data.frame(t(quantiles_nu))
colnames(quantiles_nu) <- c("low", "up")

# Add the "true" estimated smooth
plots=response_crcvm200$get_all_plots(
  baseline=baseline_crcvm200,xmin=xmin,xmax=xmax,
  link=link,xlabel=xlabel,show_CI="pointwise")
est_tau=ggplot_build(plots$fe_tau_ExpShip)$data[[1]][,c("x","y")]
est_nu=ggplot_build(plots$fe_nu_ExpShip)$data[[1]][,c("x","y")]
est_tau=cbind(est_tau,quantiles_tau)
est_nu=cbind(est_nu,quantiles_nu) 

est_tau$baseline=ggplot_build(plots$fe_tau_ExpShip)$data[[2]][,"y"]
est_nu$baseline=ggplot_build(plots$fe_nu_ExpShip)$data[[2]][,"y"]


plot_tau_response_crcvm200<- ggplot(data = est_tau) +
  geom_line(aes(x = x, y = y), color = "steelblue", size = 1) +
  geom_line(aes(x=x,y=baseline),color="steelblue",size=1,linetype="dashed")+
  geom_ribbon(aes(x = x, ymin = low, ymax = up), 
              fill = "lightblue", alpha = 0.3) +
  labs(
    x = "Distance to Ship",
    y = expression(tau)) +
  theme_minimal() +theme(
    axis.title.x = element_text(size=22),
    axis.title.y = element_text(size=22, angle=0, vjust=0.5, margin = margin(r = 10)),
    axis.text.x = element_text(size=18),
    axis.text.y = element_text(size=18),
    legend.title = element_text(size=18),
    legend.text = element_text(size=18)
  )

# Enhanced plot for nu
plot_nu_response_crcvm200 <- ggplot(data = est_nu) +
  geom_line(aes(x = x, y = y), color = "darkorange", size = 1) +
   geom_line(aes(x,baseline),color="darkorange",size=1,linetype="dashed")+
  geom_ribbon(aes(x = x, ymin = low, ymax = up), 
              fill = "navajowhite", alpha = 0.3) +
  labs(
    x = "Distance to Ship",
    y = expression(nu)) +
  theme_minimal() +theme(
    axis.title.x = element_text(size=22),
    axis.title.y = element_text(size=22, angle=0, vjust=0.5, margin = margin(r = 10)),
    axis.text.x = element_text(size=18),
    axis.text.y = element_text(size=18),
    legend.title = element_text(size=18),
    legend.text = element_text(size=18)
  )


```

```{r}

ggsave("fe_tau_ExpShip_final.pdf", plot=plot_tau_response_crcvm200,
       path="response_crcvm200", width=10, height=6, units="in")

ggsave("fe_nu_ExpShip_final.pdf", plot=plot_nu_response_crcvm200,
       path="response_crcvm200", width=10, height=6, units="in")
plot_tau_response_crcvm200
plot_nu_response_crcvm200

```

## Compute recovery distances

```{r}
make_recovery_distances_tab<-function(p) {
  
  parameter_names=names(mean_alpha)
  scaling=as.list(c(log(1-p),log(1+p)))
  names(scaling)=parameter_names
  estimates <- sapply(parameter_names,function(param) {
    mean_alpha[[param]]/scaling[[param]]})
  
  conf_intervals <- sapply(parameter_names, function(param) {
    sprintf("$[%.2f; %.2f]$", quant_alpha[[param]][1]/scaling[[param]], 
            quant_alpha[[param]][2]/scaling[[param]])
  })
  
  
  table_data <- data.frame(
    Parameter = 
      c("$D_{\\tau}^{ship}$","$D_{\\nu}^{ship}$"),
    Estimate = sprintf("$%.2f$", estimates),
    CI = conf_intervals,
    stringsAsFactors = FALSE
  )
  
  xtab <- xtable(
  table_data,
  caption = "Estimated recovery distances of the baseline values",
  label = paste0("table:recovery_distances_",p)
  )

  print(
    xtab,type="latex",
    include.rownames = FALSE,
    sanitize.text.function = identity,  
    hline.after = c(-1, 0, nrow(table_data)),
    table.placement="H"
  
  )
}

make_recovery_distances_tab(0.5)

make_recovery_distances_tab(0.1)
```
